#!/usr/bin/env python3
# test_mailbox.py — Issue353_2 M2-a/M2-b 회귀 테스트
#
# ⚠️ 글로벌 SCAR 아님 (___pm 프로젝트 소유). transcript tail → 메일박스 적재와
#   pull 프로토콜(304/205/증분)을 검증한다.
#
# 실행: python3 services/hub/test_mailbox.py
"""mailbox.py (M2-a) + /s/{h}/{sid}/mail (M2-b) 단위 테스트."""
import json
import re
import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mailbox  # noqa: E402

PASS = 0
FAIL = 0


def check(name, cond):
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f"  ok   {name}")
    else:
        FAIL += 1
        print(f"  FAIL {name}")


TMP = tempfile.mkdtemp(prefix="mailbox-test-")
JSONL = os.path.join(TMP, "sess.jsonl")


def w(*entries, partial=None):
    """엔트리를 JSONL 로 append. partial 은 개행 없이 덧붙일 미완결 조각."""
    with open(JSONL, "a", encoding="utf-8") as f:
        for e in entries:
            f.write(json.dumps(e, ensure_ascii=False) + "\n")
        if partial:
            f.write(partial)


def user(text):
    return {"type": "user", "timestamp": "2026-08-05T00:00:00Z",
            "message": {"role": "user", "content": [{"type": "text", "text": text}]}}


def assistant(*blocks):
    return {"type": "assistant", "timestamp": "2026-08-05T00:00:01Z",
            "message": {"role": "assistant", "content": list(blocks)}}


def tool_result(out):
    return {"type": "user", "timestamp": "2026-08-05T00:00:02Z",
            "message": {"role": "user",
                        "content": [{"type": "tool_result", "content": out}]}}


open(JSONL, "w").close()
box = mailbox.SessionMailbox(("h1", "s1"), JSONL)

# --- 적재 규칙 (보안·프라이버시 불변식) ---
w(user("첫 질문입니다"),
  assistant({"type": "thinking", "thinking": "비밀 추론 내용"},
            {"type": "text", "text": "답변 첫 블록"},
            {"type": "tool_use", "name": "Bash", "input": {"command": "cat /etc/passwd"}}),
  tool_result("root:x:0:0:...민감한 파일 내용..."))
added = box.sync()
kinds = [(b["kind"], b["text"]) for b in box.blocks]
check("사용자 프롬프트 → turn 블록", ("turn", "첫 질문입니다") in kinds)
check("assistant text → text 블록", ("text", "답변 첫 블록") in kinds)
check("tool_use → 도구 이름만 activity 로", ("activity", "Bash") in kinds)
check("tool_use 인자(명령)는 적재 안 함",
      not any("/etc/passwd" in b["text"] for b in box.blocks))
check("tool_result(도구 출력) 미적재",
      not any("root:x:0:0" in b["text"] for b in box.blocks))
check("thinking 미적재", not any("비밀 추론" in b["text"] for b in box.blocks))
check("적재 개수 = 3 (turn·text·activity)", added == 3 and box.max_seq == 3)

# --- 하네스 주입 컨텍스트는 턴으로 세지 않음 ---
before = box.max_seq
w(user("<system-reminder>\n메모리 인덱스 …\n</system-reminder>"),
  user("<ide_opened_file>The user opened the file /x/Issue.md</ide_opened_file>"),
  user("<command-name>/model</command-name>"),
  user("Caveat: The messages below were generated by the user while running local commands."))
box.sync()
check("system-reminder·IDE·command 주입은 turn 미생성", box.max_seq == before)
w(user("진짜 사용자 질문"))
box.sync()
check("실제 프롬프트는 turn 생성", box.max_seq == before + 1
      and box.blocks[-1]["text"] == "진짜 사용자 질문")

# --- sidechain(subagent) 제외 ---
w({"type": "assistant", "isSidechain": True, "timestamp": "t",
   "message": {"role": "assistant", "content": [{"type": "text", "text": "서브에이전트 출력"}]}})
box.sync()
check("isSidechain 엔트리 제외",
      not any("서브에이전트" in b["text"] for b in box.blocks))

# --- partial write 안전 ---
before = box.max_seq
w(assistant({"type": "text", "text": "완결 블록"}),
  partial='{"type":"assistant","message":{"content":[{"type":"text","text":"미완')
box.sync()
check("완결 라인만 적재 (미완결 꼬리 무시)",
      box.max_seq == before + 1
      and not any("미완" in b["text"] for b in box.blocks))
off_before = box.offset
# 미완결 줄이 완성되면 그때 적재된다
with open(JSONL, "a", encoding="utf-8") as f:
    f.write('결 라인이 이제 완성"}]}}\n')
box.sync()
check("다음 sync 에서 완성된 줄 적재",
      any("완성" in b["text"] for b in box.blocks) and box.offset > off_before)

# --- 무변경 판정 (파일 read 없이) ---
check("무변경 시 changed() False", box.changed() is False)
check("무변경 sync 는 0건", box.sync() == 0)

# --- 멀티바이트 경계 안전 ---
before = box.max_seq
long_ko = "한글" * 300
w(assistant({"type": "text", "text": long_ko}))
box.sync()
check("멀티바이트 텍스트 무손실",
      any(b["text"] == long_ko for b in box.blocks) and box.max_seq == before + 1)

# --- pull 프로토콜 ---
st, pay = box.read_since(0, "")
check("since=0 → 200 + 전체 블록", st == 200 and len(pay["blocks"]) == box.max_seq)
st, pay = box.read_since(box.max_seq, box.epoch)
check("최신 커서 → 304", st == 304)
st, pay = box.read_since(box.max_seq, "stale-epoch")
check("세대 불일치 → 205 Reset", st == 205 and "epoch" in pay)
st, pay = box.read_since(box.max_seq + 99, box.epoch)
check("커서가 서버보다 앞섬 → 205", st == 205)
mid = box.max_seq - 2
st, pay = box.read_since(mid, box.epoch)
check("증분만 반환 (since 초과분)",
      st == 200 and all(b["seq"] > mid for b in pay["blocks"]) and len(pay["blocks"]) == 2)
check("payload 에 epoch·max_seq·turn_active 동봉",
      pay["epoch"] == box.epoch and pay["max_seq"] == box.max_seq
      and "turn_active" in pay)

# --- truncate·파일 교체 → 세대 갱신 ---
old_epoch = box.epoch
open(JSONL, "w").close()          # truncate
w(assistant({"type": "text", "text": "새 세대 첫 블록"}))
box.sync()
check("truncate 후 세대 갱신", box.epoch != old_epoch)
check("truncate 후 seq 재시작", box.max_seq == 1)
st, _ = box.read_since(5, old_epoch)
check("구 세대 커서 → 205", st == 205)

# --- retention 밖 커서 → 205 ---
small = mailbox.SessionMailbox(("h2", "s2"), JSONL)
small.blocks = type(box.blocks)(maxlen=3)
for i in range(6):
    small._append("text", f"b{i}", "t")
check("retention 초과 시 min_seq 상승", small.min_seq > 1)
st, pay = small.read_since(0, small.epoch)
check("since=0(신규 클라)는 보유분 전체 200 + min_seq 고지",
      st == 200 and pay["min_seq"] == small.min_seq)
st, _ = small.read_since(1, small.epoch)
check("보유 하한보다 낮은 커서 → 205 (그 사이 유실)", st == 205)
st, _ = small.read_since(small.min_seq, small.epoch)
check("보유 범위 안 커서는 정상 200", st == 200)

# --- 레지스트리·GC ---
b1 = mailbox.get_box("hA", "sA", JSONL)
b2 = mailbox.get_box("hA", "sA", JSONL)
check("get_box 는 같은 세션에 같은 객체", b1 is b2)
b1.last_access = 0
check("TTL 초과 GC 제거", mailbox.gc() >= 1)
check("stats 조회 가능", isinstance(mailbox.stats().get("sessions"), int))

# --- Issue357: maybe_gc TTL 가드 (poll 경로 배선용) ---
mailbox._last_gc = 0.0
b3 = mailbox.get_box("hB", "sB", JSONL)
b3.last_access = 0
check("maybe_gc 첫 호출은 실제 GC 수행", mailbox.maybe_gc() >= 1)
b4 = mailbox.get_box("hC", "sC", JSONL)
b4.last_access = 0
check("간격 내 재호출은 스캔 없이 0 반환 (poll 폭주 방어)", mailbox.maybe_gc() == 0)
check("간격 내에는 대상이 살아 있음", ("hC", "sC") in mailbox._boxes)
check("간격 경과 후에는 다시 수행",
      mailbox.maybe_gc(now=mailbox._last_gc + mailbox.GC_MIN_INTERVAL + 1) >= 1)

# --- M2-d: 미응답 폼 판정 (_pending_ask_form 규약) ---
# 서버 핸들러는 registry 를 읽으므로 여기서는 판정 규칙만 재현 검증한다.
import time as _t


def _pick_pending(entries, cwd, now):
    """server._pending_ask_form 과 같은 규칙: 미응답 + ask 파일명 + 10분 이내 최신 1건."""
    cand, cand_ts = None, -1
    for e in entries:
        if e.get("cwd") != cwd or e.get("answered"):
            continue
        base = os.path.basename(e.get("path", ""))
        if not (base.startswith("claude-htm-ask-") or "_b_" in base):
            continue
        m = re.search(r"(\d{9,})", base)
        ts = int(m.group(1)) if m else 0
        if ts > cand_ts:
            cand, cand_ts = e, ts
    return cand


now = int(_t.time())
ents = [
    {"cwd": "/p", "path": f"/p/_doc_work/htm/claude-htm-ask-{now-100}.html"},
    {"cwd": "/p", "path": f"/p/_doc_work/htm/claude-htm-ask-{now-50}.html"},
    {"cwd": "/p", "path": f"/p/_doc_work/htm/hub_htm_{now-10}_a_x.htm"},
    {"cwd": "/other", "path": f"/other/_doc_work/htm/claude-htm-ask-{now}.html"},
]
pick = _pick_pending(ents, "/p", now)
check("폼 판정: 같은 cwd 의 최신 ask 선택",
      pick and str(now - 50) in pick["path"])
check("폼 판정: a모드 문서는 폼 아님", pick and "_a_" not in pick["path"])
ents[1]["answered"] = True
pick2 = _pick_pending(ents, "/p", now)
check("폼 판정: answered 는 후보 제외 (1회 소비 = first-wins)",
      pick2 and str(now - 100) in pick2["path"])
for e in ents:
    e["answered"] = True
check("폼 판정: 모두 응답됨 → None", _pick_pending(ents, "/p", now) is None)

print()
print(f"PASS={PASS} FAIL={FAIL}")
sys.exit(1 if FAIL else 0)
